update

diff --git a/roles/vb/files/db_check/shell/check_os b/roles/vb/files/db_check/shell/check_os
--- a/roles/vb/files/db_check/shell/check_os
+++ b/roles/vb/files/db_check/shell/check_os
@@ -50,8 +50,9 @@ ipv4_regexp='(([0-9]|[0-9]{2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[0-9]{2
 #==============================================================#
 
 
-echo "---" > ${PWD}/roles/vb/vars/main.yml
-echo "# vars file for vb" >> ${PWD}/roles/vb/vars/main.yml
+#远程服务器执行应该返回json方式 后续规划
+#echo "---" 
+#echo "# vars file for vb" 
  
 
 #----------------------------------------------#
@@ -61,8 +62,8 @@ function check_kernel(){
     local kernel_name=$(uname -s)
     if [[ "${kernel_name}" == "Linux" ]]; then
         log_info "kernel = ${kernel_name}"
-        echo "#kernel" >> ${PWD}/roles/vb/vars/main.yml
-        echo "kernel_name: $(uname -s)"  >> ${PWD}/roles/vb/vars/main.yml
+        #echo "#kernel" 
+        #echo "kernel_name: $(uname -s)"  
         return 0
     else
         log_error "kernel = ${kernel_name}, not supported, Linux only"
@@ -78,11 +79,11 @@ function check_machine(){
     local machine_name=$(uname -m)
     if [[ "${machine_name}" == "x86_64" ]]; then
         log_info "machine = ${machine_name}"
-        echo "machine_name: $(uname -m)" >> ${PWD}/roles/vb/vars/main.yml
+        #echo "machine_name: $(uname -m)" 
         return 0
     elif [[ "${machine_name}" == "aarch64" ]]; then
         log_info "machine = ${machine_name}"
-        echo "machine_name: $(uname -m)" >> ${PWD}/roles/vb/vars/main.yml
+        #echo "machine_name: $(uname -m)" 
         return 0
     else
         log_error "machine = ${machine_name}, not supported, x86_64&aarch64 only"
@@ -104,11 +105,11 @@ function check_release(){
         eval "$line"
     done < /etc/os-release
     if [[ "${NAME}" == 'CentOS Linux' ]]; then
-        echo "os_name: ${NAME}" >> ${PWD}/roles/vb/vars/main.yml
+        echo "os_name: ${NAME}"
         local full=`cat /etc/centos-release | tr -dc '0-9.'`
         local major=$(cat /etc/centos-release | tr -dc '0-9.'|cut -d \. -f1)
         local minor=$(cat /etc/centos-release | tr -dc '0-9.' |cut -d \.  -f 1,2)
-        echo "os_version=$(cat /etc/centos-release | tr -dc '0-9.' |cut -d \.  -f 1,2)" ${PWD}/roles/vb/vars/main.yml
+        #echo "os_version=$(cat /etc/centos-release | tr -dc '0-9.' |cut -d \.  -f 1,2)" 
         if [[ ${major} != "7" ]]; then
             log_error "release = ${full} , only 7 is supported"
             exit 4
@@ -123,8 +124,8 @@ function check_release(){
         fi
         return 0
     elif [[ "${NAME}" == 'openEuler' ]];then
-        echo "os_name: ${NAME}" >> ${PWD}/roles/vb/vars/main.yml
-        echo ""
+        #echo "os_name: ${NAME}" 
+        #echo ""
         local full=`cat /etc/openEuler-release | tr -dc '0-9.'`
         local asynchronous=$(uname -a |awk '{print $3}'|cut -d \- -f1)
         if [[ ${asynchronous} == '4.19.90' ]];then 
@@ -166,8 +167,8 @@ function check_sudo(){
 
 
 function check_mem(){
-    echo "mem_info: $(cat /proc/meminfo |grep MemTotal|awk '{print $2}')" >> ${PWD}/roles/vb/vars/main.yml
-    echo "page_size: $(getconf PAGE_SIZE)" >> ${PWD}/roles/vb/vars/main.yml
+    #echo "mem_info: $(cat /proc/meminfo |grep MemTotal|awk '{print $2}')" 
+    #echo "page_size: $(getconf PAGE_SIZE)" 
     if [[ ! -f /proc/meminfo ]]; then
         log_error "mem = unknown, /proc/meminfo not exists"
         exit 6
@@ -190,6 +191,23 @@ function check_secure(){
     
 }
 
+#======================================================#
+# check python version whetther supported
+#======================================================#
+function python_version(){
+    local py_version=$(python3 --version)
+    if [[ $? -eq 0 ]];then
+        log_info  ${py_version} "python  is OK"
+        local py_modle=$(pip3 list --format=columns|grep -E "docxtpl"|wc -l)
+        if [[ ${py_modle} -eq 0 ]];then
+            log_error "[vastbase-52200] : Unable to import module"
+        fi
+    else
+        log_error  py2_version=`python --version`
+        log_error "[vastbase-52201] : The current python version is not supported."
+        exit 7
+    fi        
+}
 
 #========================================#
 # main
@@ -206,6 +224,7 @@ function main(){
     check_sudo       # current_user  = NOPASSWD sudo
     check_mem        # mem_info      = KB
     check_secure     # secure
+    python_version   # python
     log_hint "configure Aliceauto done. Use 'make install' to proceed\n"
 
 }
